-- ============================================
-- DC-FMS Seed Data — DISABLED
-- Seed data intentionally removed during patient-registry work.
-- The database starts empty; all data is created through the UI.
-- Default past-medical-history options are inserted by migration
-- 20260924190000_initial_schema.sql instead.
-- Run: supabase db seed (currently a no-op)
-- ============================================
